import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Utensils, Sparkles, Loader2, Apple, Heart, Target, ClipboardCheck, ClipboardList } from 'lucide-react';
import { GoogleGenerativeAI } from "@google/generative-ai";

const GEMINI_API_KEY = "AIzaSyB7H5bhn8y8Z4Ah-vTCqnMNWVw6ovxTrDs".trim();
const genAI = new GoogleGenerativeAI(GEMINI_API_KEY);
const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });

const DietaryPlans = () => {
  const [goal, setGoal] = useState("Weight Loss");
  const [pref, setPref] = useState("Veg");
  const [loading, setLoading] = useState(false);
  const [plan, setPlan] = useState("");

  const generatePlan = async () => {
    setLoading(true);
    setPlan("");

    const prompt = `Generate a ONE-DAY personalized dietary plan for a health goal: ${goal} and dietary preference: ${pref}. 
    Include Breakfast, Lunch, Dinner, and 2 healthy snacks. 
    Format it with clear bold headers and bullet points. 
    Keep it professional and nutritionally balanced. 
    Add one "Expert Health Tip" at the end.`;

    try {
      const result = await model.generateContent(prompt);
      const response = await result.response;
      setPlan(response.text());
    } catch (e) {
      setPlan("Error generating plan. Please try again later. 🍎");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="max-w-6xl mx-auto font-sans pb-20">
      <div className="mb-14 flex justify-between items-end pb-6 border-b border-gray-100">
        <div className="max-w-2xl">
          <h2 className="text-2xl font-extrabold text-secondary mb-3 uppercase tracking-tight">🥗 AI Dietary Plans</h2>
          <p className="text-sm font-bold text-text-dim italic leading-relaxed">
            Get a 24-hour nutrition roadmap generated by CareBot specifically for your health goals.
          </p>
        </div>
        <div className="hidden lg:block">
           <div className="bg-primary/10 px-4 py-2 rounded-2xl border border-primary/20 flex items-center gap-2 text-primary font-bold">
              <ClipboardList size={20} /> AI Nutritionist Online
           </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 mb-10">
        <div className="lg:col-span-1 space-y-6">
           <div className="bg-white p-6 rounded-[2.5rem] border border-border shadow-sm">
              <h3 className="text-xl font-bold text-secondary mb-6 flex items-center gap-2">
                <Target size={20} className="text-primary" /> Nutrition Profile
              </h3>
              
              <div className="space-y-4">
                <div>
                  <label className="block text-[10px] font-black text-gray-400 uppercase tracking-widest mb-2 ml-1">Health Goal</label>
                  <select 
                    value={goal}
                    onChange={(e) => setGoal(e.target.value)}
                    className="w-full bg-gray-50 border border-border p-3.5 rounded-2xl font-bold text-secondary outline-none focus:border-primary transition-all shadow-sm"
                  >
                    <option>Weight Loss</option>
                    <option>Diabetes Friendly</option>
                    <option>Heart Healthy</option>
                    <option>Muscle Gain</option>
                  </select>
                </div>

                <div>
                  <label className="block text-[10px] font-black text-gray-400 uppercase tracking-widest mb-2 ml-1">Dietary Preference</label>
                  <select 
                    value={pref}
                    onChange={(e) => setPref(e.target.value)}
                    className="w-full bg-gray-50 border border-border p-3.5 rounded-2xl font-bold text-secondary outline-none focus:border-primary transition-all shadow-sm"
                  >
                    <option>Veg</option>
                    <option>Non-Veg</option>
                    <option>Vegan</option>
                    <option>Paleo</option>
                  </select>
                </div>

                <button 
                  onClick={generatePlan}
                  disabled={loading}
                  className="w-full mt-4 bg-primary text-white p-4 rounded-2xl font-black shadow-lg hover:bg-green-700 transition-all flex items-center justify-center gap-2 disabled:opacity-50"
                >
                  {loading ? <Loader2 className="animate-spin" size={20} /> : <Sparkles size={20} />} 
                  {loading ? 'GENERICING PLAN...' : 'GENERATE MY PLAN'}
                </button>
              </div>
           </div>

           <div className="bg-secondary p-8 rounded-[2.5rem] text-white">
              <div className="w-12 h-12 bg-white/10 rounded-2xl flex items-center justify-center mb-6"><Apple size={24} className="text-primary" /></div>
              <h4 className="text-xl font-bold mb-2">Smart Nutrition</h4>
              <p className="text-gray-400 font-bold leading-relaxed mb-6 italic">"Good health is not something we can buy. However, it can be a valuable savings account."</p>
              <div className="flex -space-x-2">
                 {[1,2,3,4].map(i => <div key={i} className="w-8 h-8 rounded-full border-2 border-secondary overflow-hidden bg-gray-200"><img src={`https://api.dicebear.com/7.x/avataaars/svg?seed=Food${i}`} alt="user" /></div>)}
                 <div className="w-8 h-8 rounded-full border-2 border-secondary bg-primary text-[10px] font-black flex items-center justify-center">+2k Users</div>
              </div>
           </div>
        </div>

        <div className="lg:col-span-2">
           <AnimatePresence mode="wait">
              {!plan && !loading ? (
                 <motion.div 
                   initial={{ opacity: 0 }} animate={{ opacity: 1 }} 
                   className="h-full min-h-[400px] flex flex-col items-center justify-center bg-gray-50 rounded-[2.5rem] border-2 border-dashed border-border p-12 text-center"
                 >
                    <div className="w-20 h-20 bg-white shadow-xl rounded-3xl flex items-center justify-center mb-6 text-primary border border-gray-100">
                      <ClipboardCheck size={32} />
                    </div>
                    <h3 className="text-2xl font-bold text-secondary mb-2">Ready to generate your plan?</h3>
                    <p className="text-text-dim font-bold max-w-sm italic tracking-tight">Select your goals and hit the generate button to receive your AI nutrition guide.</p>
                 </motion.div>
              ) : (
                <motion.div
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="bg-white p-10 rounded-[2.5rem] border border-border shadow-soft h-full relative group"
                >
                   {loading ? (
                     <div className="h-full min-h-[400px] flex flex-col items-center justify-center gap-4">
                        <Loader2 className="animate-spin text-primary" size={48} />
                        <span className="font-black text-secondary tracking-widest uppercase text-xs">CareBot is formulating your nutrition guide...</span>
                     </div>
                   ) : (
                     <div className="relative z-10">
                        <div className="flex justify-between items-start mb-8">
                           <div className="bg-primary px-4 py-1.5 rounded-full text-white text-[10px] font-black uppercase tracking-widest">Personalized Guide</div>
                           <button 
                             onClick={() => {
                               navigator.clipboard.writeText(plan);
                               alert("Dietary Plan copied to clipboard! 📋");
                             }}
                             className="text-text-dim font-black text-[10px] hover:text-primary transition-colors flex items-center gap-1 uppercase tracking-widest"
                           >
                             <ClipboardCheck size={14} /> Copy Plan
                           </button>
                        </div>
                        <div 
                          className="prose prose-slate max-w-none prose-headings:text-secondary prose-p:text-text-dim prose-p:font-bold prose-p:leading-relaxed prose-li:text-text-dim prose-li:font-bold prose-strong:text-secondary text-lg"
                          dangerouslySetInnerHTML={{ __html: plan.replace(/\n/g, '<br/>') }}
                        />
                     </div>
                   )}
                   <div className="absolute top-0 right-0 p-10 opacity-5 pointer-events-none group-hover:opacity-10 transition-opacity"><Utensils size={160} /></div>
                </motion.div>
              )}
           </AnimatePresence>
        </div>
      </div>
    </div>
  );
};

export default DietaryPlans;
